### Numpy Library

- Processing N-Dimensional arrays

In [5]:
import numpy as np

li = [1,2,3, 'z']

a = np.array(li)

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:


m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]


1

In [21]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

648

In [22]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
c = b.reshape(5,3)

In [27]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
d = c + 1
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [29]:
import numpy as np
M = np.ones((3, 3))
print("Matrix M:\n",M)

Matrix M:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


### Pandas

**Use Cases**
- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- Series
- DataFrames

In [32]:
import pandas as pd


internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [37]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [38]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [41]:
final.columns # Names of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [42]:
final.values # Lists of all rows

array([[21, 15],
       [18, 18],
       [24, 12]])

In [43]:
final.values[2]

array([24, 12])

In [52]:
final.values[2,0] = 25
final.values[2][0]


25

In [47]:

for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])


Internal1 -  21 , Internal2 -  15
Internal1 -  18 , Internal2 -  18
Internal1 -  24 , Internal2 -  12


In [48]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [50]:
final.loc['s4'] = [20, 18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
3          15         18
s4         20         18

In [51]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
s4         20         18

In [53]:
final


Internal1  Internal2
s1         21         15
s2         18         18
s3         25         12
3          15         18
s4         20         18

In [54]:
final = final.drop(3)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         25         12
s4         20         18

In [55]:
final.values[2] = [12,25]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         12         25
s4         20         18

In [56]:

# Reading CSV file data
import pandas as pd
filepath = 'DataFiles/Income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [58]:

# Extract income of all states in 2013

#California : 57528

for row in incomedf.values:
    print(row[1], ':', row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [59]:
# Average income of Arizona

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
    
sum/len(incomedf.values[2][2:])

47214.77777777778

In [60]:
# Average income of all states in year 2012

sum = 0
for row in incomedf.values:
    sum += row[-2]
    
sum/len(incomedf.values)


50038.8